[package]
name = "librqbit-lsd"
version = "0.1.0"
edition = "2024"

[features]
default = ["sha1-crypto-hash"]
sha1-crypto-hash = [
    "librqbit-sha1-wrapper/sha1-crypto-hash",
    "librqbit-core/sha1-crypto-hash",
]
sha1-ring = ["librqbit-sha1-wrapper/sha1-ring", "librqbit-core/sha1-ring"]

[dependencies]
anyhow = "1.0.98"
librqbit-dualstack-sockets = { version = "0.4.0" }
tokio = { version = "1.45.1", features = ["time"] }
tokio-util = "0.7.15"
librqbit-sha1-wrapper = { path = "../sha1w", version = "4", default-features = false }
librqbit-core = { version = "5", path = "../librqbit_core", default-features = false }
rand = "0.9.1"
futures = "0.3.31"
bstr = "1.12.0"
parking_lot = "0.12.4"
httparse = "1.10.1"
atoi = "2.0.0"
tracing = "0.1.41"

[dev-dependencies]
tracing-subscriber = "0.3.19"
