[package]
name = "librqbit-lsd"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
librqbit-dualstack-sockets = "0.3.1"
tokio = { version = "1.45.1", features = ["time"] }
tokio-util = "0.7.15"
librqbit-core = { path = "../librqbit_core", default-features = false, version = "5" }
